### ISSUE TITLE
Install the latest version using conda.

### ISSUE THREAD

**Issue by YukiSakai1209** [pog87/PtitPrince#18]
@pog87 Would it be possible to update the conda version?
I'm running into the issue below now since I got version 0.2.3 from conda
https://github.com/pog87/PtitPrince/issues/14

**Comment by sappelhoff** [comment]
it would perhaps be worth it to make this package available from https://conda-forge.org/ ... that way the conda packages can be automaticallly updated whenever a new pypi version of ptitprince is released.

**Comment by pog87** [comment]
@sappelhoff if you're experienced w/ the pip-to-condaforge procedure `and` the update would be auto, I have nothing against it.

**Comment by sappelhoff** [comment]
okay, let's see how this goes: https://github.com/conda-forge/staged-recipes/pull/14047

**Comment by sappelhoff** [comment]
ptitprince 0.2.5 can now be installed from conda-forge using `conda install -c conda-forge ptitprince`, see the "feedstock": https://github.com/conda-forge/ptitprince-feedstock

now whenever a new version of `ptitprince` is pushed to pypi, the conda-forge bot will open a PR against the ptitprince feedstock repo to "bump" the conda version automatically. Once that happens, @pog87 and me will get a notification to merge that PR.

I could make a PR tomorrow to add some badges and instructions to the README of ptitprince, so that people are aware about this new feature.

**Comment by pog87** [comment]
thanks a lot for your help @sappelhoff 👍👍
